using JMayer.Data.Data;
using System.Net;

namespace JMayer.Data.HTTP.DataLayer;

/// <summary>
/// The class represents the result for a remote operation.
/// </summary>
public sealed class OperationResult
{
    /// <summary>
    /// The property gets the data object returned by the operation.
    /// </summary>
    public DataObject? DataObject { get; private init; }

    /// <summary>
    /// The property gets if the operation was a success.
    /// </summary>
    public bool IsSuccessStatusCode => StatusCode == HttpStatusCode.OK;

    /// <summary>
    /// The property gets the user friendly details of a problem that occurred on the server.
    /// </summary>
    public string? ProblemDetails { get; private init; }

    /// <summary>
    /// The property gets the HTTP status code returned by the remote operation.
    /// </summary>
    public HttpStatusCode StatusCode { get; private init; }

    /// <summary>
    /// The property gets any validation errors generated by the server.
    /// </summary>
    public Dictionary<string, string[]> ValidationErrors { get; private init; } = [];

    /// <summary>
    /// The property constructor.
    /// </summary>
    /// <param name="httpStatusCode">The HTTP status code returned by the remote operation.</param>
    /// <param name="dataObject">The data object returned by the operation.</param>
    /// <param name="problemDetails">The user friendly details of a problem that occurred on the server.</param>
    /// <param name="validationErrors">Any validation errors generated by the server.</param>
    public OperationResult(HttpStatusCode httpStatusCode, DataObject? dataObject = null, string? problemDetails = null, Dictionary<string, string[]>? validationErrors = null)
    {
        DataObject = dataObject;
        ProblemDetails = problemDetails;
        StatusCode = httpStatusCode;
        ValidationErrors = validationErrors ?? [];
    }
}
