# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: MainWorkflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Add GitHub Nuget Source
      run: dotnet nuget add source --username jmayer913 --password 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 --store-password-in-clear-text --name github "https://nuget.pkg.github.com/JMayer-Data-Library/index.json"
      continue-on-error: true
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    - name: Package
      run: dotnet pack --configuration Release
    - name: Publish
      run: dotnet nuget push "**/*.nupkg" --api-key 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 --source "github"
